#result state
stop: [1,0]
walk: [0,1]

#chan 1 is on column (col start at 0)
first_chan: 7
decoded: 3
cue: 5
stim: 4

#kohonen classifier parameter
kc_col: 12
kc_row: 7
kc_max_weight: 5
kc_alpha: 0.1
kc_neighbor: 3
kc_min_win: 2

#col 3 state (col start at 0)
stop_healthy: ['1','-4','0']
init_healthy: ['2']
walk_healthy: ['-2']

#col 5 state (col start at 0)
stop_SCI: ['0','3','4']
init_SCI: ['1','2']
walk_SCI: ['2']